# Generated by Django 6.0.4 on 2026-05-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmcode',
            old_name='is_active',
            new_name='is_confirmed',
        ),
    ]
